# Generated by Django 4.2.7 on 2023-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(max_length=128)),
                ('elastic_user', models.CharField(max_length=32)),
                ('elastic_password', models.CharField(max_length=32)),
            ],
        ),
    ]
