# Generated by Django 4.2.7 on 2023-11-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=15, verbose_name='Bank account type')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=32)),
                ('address_line_two', models.CharField(max_length=32, null=True)),
                ('suburb', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=21, verbose_name='Bank account number')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinebanking.bankaccounttype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinebanking.customer')),
            ],
        ),
    ]
