# Generated by Django 4.2.7 on 2023-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0002_customeraddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttype',
            name='transactional',
            field=models.BooleanField(default=0),
        ),
    ]
