# Generated by Django 4.2.7 on 2023-11-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0003_bankaccounttype_transactional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=12)),
                ('transaction_operator', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='transactional',
            field=models.BooleanField(default=0, verbose_name='Transactional field'),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('transaction_value', models.FloatField(default=0)),
                ('closing_balance', models.FloatField(default=0)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinebanking.bankaccount')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinebanking.accounttransactiontype')),
            ],
        ),
    ]
