# Generated by Django 4.2.7 on 2023-11-27 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0004_accounttransactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
