# Generated by Django 4.2.7 on 2023-11-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0005_accounttransaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='description',
            field=models.CharField(max_length=512),
        ),
    ]
