# Generated by Django 4.2.7 on 2023-11-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0007_transactioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='transaction_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onlinebanking.transactioncategory'),
        ),
    ]
