# Generated by Django 4.2.7 on 2023-12-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0009_accounttransaction_exported_bankaccount_exported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('dominant_operational_format', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
