# Generated by Django 4.2.7 on 2023-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0010_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
    ]
