# Generated by Django 4.2.7 on 2023-12-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0011_accounttransaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='weight',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
