# Generated by Django 4.2.7 on 2024-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0013_bankingproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingproducts',
            name='exported',
            field=models.BooleanField(default=False),
        ),
    ]
