# Generated by Django 4.2.7 on 2024-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0014_bankingproducts_exported'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoScenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=56)),
                ('user_geography', models.CharField(max_length=56)),
                ('custom_attributes', models.CharField(max_length=128)),
                ('active', models.BooleanField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bankingproducts',
            name='generator_keywords',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
