# Generated by Django 4.2.7 on 2024-05-22 11:11

from django.db import migrations

def load_initial_data(apps, schema_editor):
    transaction_type = apps.get_model('onlinebanking', 'AccountTransactionType')
    transaction_type.objects.create(
        transaction_type = 'Credit',
        transaction_operator = '+',
    )
    transaction_type.objects.create(
        transaction_type = 'Debit',
        transaction_operator = '-',
    )

    transaction_type = apps.get_model('onlinebanking', 'TransactionCategory')
    transaction_type.objects.create(
        category_name = 'EFT',
        weight = '7',
    )
    transaction_type.objects.create(
        category_name = 'Purchase',
        weight = '90',
    )
    transaction_type.objects.create(
        category_name = 'Transfer',
        weight = '3',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0015_demoscenarios_bankingproducts_generator_keywords'),
    ]

    operations = [
           migrations.RunPython(load_initial_data),
    ]
