# Generated by Django 4.2.7 on 2024-05-23 08:15

from django.db import migrations


def load_initial_data(apps, schema_editor):
    bank_account_type = apps.get_model('onlinebanking', 'BankAccountType')
    bank_account_type.objects.create(
        account_type = 'Savings',
        transactional = 0,
    )
    bank_account_type.objects.create(
        account_type = 'Transmission',
        transactional = 1,
    )
    bank_account_type.objects.create(
        account_type = 'Credit',
        transactional = 1,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0016_staticData'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
