# Generated by Django 4.2.7 on 2024-05-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebanking', '0017_account_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=32, verbose_name='Bank account number'),
        ),
    ]
